# Veri Bilimi İş İlanları ve Becerileri (2024): Veri Temizleme ve Analiz

Bu çalışmada Kaggle'daki "Data Science Job Postings & Skills (2024)" veri setini kullanıyorum. Veri, LinkedIn'den derlenmiş ham bir iş ilanı dökümü ve üç CSV dosyasından oluşuyor:

- `job_postings.csv`: ilan başlığı, şirket, konum, seviye ve çalışma tipi gibi temel bilgiler
- `job_skills.csv`: her ilanda istenen beceriler
- `job_summary.csv`: ilanın tam metni (özet)

**Amacım:** Üç tabloyu birleştirip temizlemek, ardından veri bilimi ve machine learning alanında hangi becerilerin  öne çıktığını görselleştirmek. Bu notebook aynı zamanda pandas ile veri temizleme pratiğimdir.

## 1. Kütüphaneler ve veri yükleme
Veriyi okumak ve işlemek için `pandas`, sayısal işlemler için `numpy` kullanıyorum. Görselleştirme kütüphanelerini analiz bölümünde ekleyeceğim.

In [1]:
import pandas as pd # Import Pandas for data manipulation and analysis
import numpy as np # Import NumPy for handling numerical operations

In [2]:
import plotly.io as pio
pio.renderers.default = "notebook_connected"

## 2. Tabloların ilk incelemesi
Her dosyayı önce ayrı ayrı okuyup tanıyorum. Her biri için sırasıyla `head()`, `shape`, `info()`, eksik değer ve tekrar eden satır kontrollerini yapıyorum. Birleştirmeye ancak üç tabloyu da tanıdıktan sonra geçeceğim.

In [3]:
df_posting=pd.read_csv("/kaggle/input/datasets/asaniczka/data-science-job-postings-and-skills/job_postings.csv")

In [4]:
df_posting

,job_link,last_processed_time,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
0,https://www.linkedin.com/jobs/view/senior-mach...,2024-01-21 08:08:48.031964+00,Finished NER,t,t,f,Senior Machine Learning Engineer,Jobs for Humanity,"New Haven, CT",2024-01-14,East Haven,United States,Agricultural-Research Engineer,Mid senior,Onsite
1,https://www.linkedin.com/jobs/view/principal-s...,2024-01-20 04:02:12.331406+00,Finished NER,t,t,f,"Principal Software Engineer, ML Accelerators",Aurora,"San Francisco, CA",2024-01-14,El Cerrito,United States,Set-Key Driver,Mid senior,Onsite
2,https://www.linkedin.com/jobs/view/senior-etl-...,2024-01-21 08:08:31.941595+00,Finished NER,t,t,f,Senior ETL Data Warehouse Specialist,Adame Services LLC,"New York, NY",2024-01-14,Middletown,United States,Technical Support Specialist,Associate,Onsite
3,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:30:55.796572+00,Finished NER,t,t,f,Senior Data Warehouse Developer / Architect,Morph Enterprise,"Harrisburg, PA",2024-01-12,Lebanon,United States,Architect,Mid senior,Onsite
4,https://www.linkedin.com/jobs/view/lead-data-e...,2024-01-21 08:08:58.312124+00,Finished NER,t,t,f,Lead Data Engineer,Dice,"Plano, TX",2024-01-14,McKinney,United States,Maintenance Data Analyst,Mid senior,Onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12212,https://uk.linkedin.com/jobs/view/data-reporti...,2024-01-21 07:11:22.099082+00,Finished NER,t,t,f,"Data Reporting Manager, FOOTBALL ASSOCIATION",Guardian Jobs,"Wembley, England, United Kingdom",2024-01-16,High Wycombe,United Kingdom,Manager Forms Analysis,Mid senior,Onsite
12213,https://www.linkedin.com/jobs/view/corporate-a...,2024-01-19 15:10:41.177008+00,Finished NER,t,t,f,Corporate AML Alert Investigation Specialist,"Glacier Bancorp, Inc.","Kalispell, MT",2024-01-14,Montana,United States,Teller,Mid senior,Onsite
12214,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:20:19.036168+00,Finished NER,t,t,f,Senior Data Scientist,Highnote,"San Francisco, CA",2024-01-16,San Rafael,United States,Mathematician,Mid senior,Onsite
12215,https://www.linkedin.com/jobs/view/senior-data...,2024-01-19 23:25:28.107523+00,Finished NER,t,t,f,Senior Data Engineer,CompSource Mutual Insurance Company,"Oklahoma City, OK",2024-01-16,Arcadia,United States,Protection Engineer,Mid senior,Onsite
12216,https://www.linkedin.com/jobs/view/medical-tec...,2024-01-19 23:26:27.593516+00,Finished NER,t,t,f,"Medical Technologist, MLS or MLT",Community Health Systems,"Mooresville, NC",2024-01-14,Salisbury,United States,Biologist,Mid senior,Onsite

In [5]:
df_posting.head()

,job_link,last_processed_time,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
0,https://www.linkedin.com/jobs/view/senior-mach...,2024-01-21 08:08:48.031964+00,Finished NER,t,t,f,Senior Machine Learning Engineer,Jobs for Humanity,"New Haven, CT",2024-01-14,East Haven,United States,Agricultural-Research Engineer,Mid senior,Onsite
1,https://www.linkedin.com/jobs/view/principal-s...,2024-01-20 04:02:12.331406+00,Finished NER,t,t,f,"Principal Software Engineer, ML Accelerators",Aurora,"San Francisco, CA",2024-01-14,El Cerrito,United States,Set-Key Driver,Mid senior,Onsite
2,https://www.linkedin.com/jobs/view/senior-etl-...,2024-01-21 08:08:31.941595+00,Finished NER,t,t,f,Senior ETL Data Warehouse Specialist,Adame Services LLC,"New York, NY",2024-01-14,Middletown,United States,Technical Support Specialist,Associate,Onsite
3,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:30:55.796572+00,Finished NER,t,t,f,Senior Data Warehouse Developer / Architect,Morph Enterprise,"Harrisburg, PA",2024-01-12,Lebanon,United States,Architect,Mid senior,Onsite
4,https://www.linkedin.com/jobs/view/lead-data-e...,2024-01-21 08:08:58.312124+00,Finished NER,t,t,f,Lead Data Engineer,Dice,"Plano, TX",2024-01-14,McKinney,United States,Maintenance Data Analyst,Mid senior,Onsite

In [6]:
df_posting.shape

(12217, 15)

In [7]:
df_posting.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12217 entries, 0 to 12216
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_link             12217 non-null  object
 1   last_processed_time  12217 non-null  object
 2   last_status          12217 non-null  object
 3   got_summary          12217 non-null  object
 4   got_ner              12217 non-null  object
 5   is_being_worked      12217 non-null  object
 6   job_title            12217 non-null  object
 7   company              12217 non-null  object
 8   job_location         12216 non-null  object
 9   first_seen           12217 non-null  object
 10  search_city          12217 non-null  object
 11  search_country       12217 non-null  object
 12  search_position      12217 non-null  object
 13  job_level            12217 non-null  object
 14  job_type             12217 non-null  object
dtypes: object(15)
memory usage: 1.4+ MB

In [8]:
df_posting.isnull().sum()

job_link               0
last_processed_time    0
last_status            0
got_summary            0
got_ner                0
is_being_worked        0
job_title              0
company                0
job_location           1
first_seen             0
search_city            0
search_country         0
search_position        0
job_level              0
job_type               0
dtype: int64

In [9]:
df_posting.duplicated().sum()

np.int64(0)

**Gözlemler (job_postings):**
- Tablo **12.217 satır ve 15 sütundan** oluşuyor.
- Tekrar eden satır yok (`duplicated().sum()` = 0).
- Sadece `job_location` sütununda **1 eksik değer** var, diğer sütunlar tam dolu.
- Tüm sütunlar `object` olarak okunmuş. `last_processed_time` ve `first_seen` aslında **tarih**, `got_summary`, `got_ner` ve `is_being_worked` ise `t/f` değerli **mantıksal (boolean)** sütunlar. Bu dönüşümleri temizleme bölümünde yapacağım.

### 2.2 job_skills

In [10]:
df_skills=pd.read_csv("/kaggle/input/datasets/asaniczka/data-science-job-postings-and-skills/job_skills.csv")

In [11]:
df_skills

,job_link,job_skills
0,https://www.linkedin.com/jobs/view/senior-mach...,"Machine Learning, Programming, Python, Scala, ..."
1,https://www.linkedin.com/jobs/view/principal-s...,"C++, Python, PyTorch, TensorFlow, MXNet, CUDA,..."
2,https://www.linkedin.com/jobs/view/senior-etl-...,"ETL, Data Integration, Data Transformation, Da..."
3,https://www.linkedin.com/jobs/view/senior-data...,"Data Lakes, Data Bricks, Azure Data Factory Pi..."
4,https://www.linkedin.com/jobs/view/lead-data-e...,"Java, Scala, Python, RDBMS, NoSQL, Redshift, S..."
...,...,...
12212,https://uk.linkedin.com/jobs/view/data-reporti...,"Dashboard development, Reporting, Power BI, SQ..."
12213,https://www.linkedin.com/jobs/view/corporate-a...,"Investigation, Antimoney laundering, Fraud, Ba..."
12214,https://www.linkedin.com/jobs/view/senior-data...,"Data Science, Quantitative Modeling, SQL, Data..."
12215,https://www.linkedin.com/jobs/view/senior-data...,"Data Engineering, Data Quality, SQL, Python, T..."
12216,https://www.linkedin.com/jobs/view/medical-tec...,"Medical Technology, MLS, Microbiology, Clinica..."

In [12]:
df_skills.isnull().sum()

job_link      0
job_skills    5
dtype: int64

In [13]:
df_skills.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12217 entries, 0 to 12216
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   job_link    12217 non-null  object
 1   job_skills  12212 non-null  object
dtypes: object(2)
memory usage: 191.0+ KB

In [14]:
df_skills.shape

(12217, 2)

In [15]:
df_skills.duplicated().sum()

np.int64(0)

**Gözlemler (job_skills):**
- Tablo **12.217 satır ve 2 sütundan** (`job_link`, `job_skills`) oluşuyor.
- Tekrar eden satır yok.
- `job_skills` sütununda **5 eksik değer** var, `job_link` tam dolu.
- Beceriler her ilan için **virgülle ayrılmış tek bir metin** olarak tutulmuş. Becerileri tek tek saymak için bu metni bölmem gerekecek.

### 2.3 df_summary

In [16]:
df_summary=pd.read_csv("/kaggle/input/datasets/asaniczka/data-science-job-postings-and-skills/job_summary.csv")

In [17]:
df_summary

,job_link,job_summary
0,https://www.linkedin.com/jobs/view/senior-mach...,Company Description\nJobs for Humanity is part...
1,https://www.linkedin.com/jobs/view/principal-s...,Who We Are\nAurora (Nasdaq: AUR) is delivering...
2,https://www.linkedin.com/jobs/view/senior-etl-...,"Location: New York City, NY\nPosition Summary\..."
3,https://www.linkedin.com/jobs/view/senior-data...,Responsibilities:\nCandidate must have signifi...
4,https://www.linkedin.com/jobs/view/lead-data-e...,Dice is the leading career destination for tec...
...,...,...
12212,https://uk.linkedin.com/jobs/view/data-reporti...,"FOOTBALL ASSOCIATION\nMake an impact, on and o..."
12213,https://www.linkedin.com/jobs/view/corporate-a...,About The Role\nPlease note: review of applica...
12214,https://www.linkedin.com/jobs/view/senior-data...,About Highnote\nFounded in 2020 by a team of l...
12215,https://www.linkedin.com/jobs/view/senior-data...,Are you an experienced data engineer in Oklaho...
12216,https://www.linkedin.com/jobs/view/medical-tec...,Job Description\nWeekend night shift position ...

In [18]:
df_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12217 entries, 0 to 12216
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   job_link     12217 non-null  object
 1   job_summary  12217 non-null  object
dtypes: object(2)
memory usage: 191.0+ KB

In [19]:
df_summary.shape

(12217, 2)

In [20]:
df_summary.isnull().sum()

job_link       0
job_summary    0
dtype: int64

In [21]:
df_summary.duplicated().sum()

np.int64(0)

In [22]:
df_summary.duplicated(subset=["job_summary"],keep=False).sum()

np.int64(3277)

**Gözlemler (job_summary):**
- Tablo **12.217 satır ve 2 sütundan** (`job_link`, `job_summary`) oluşuyor.
- Eksik değer ve tekrar eden satır yok.
- `job_summary` sütununda 12.217 satıra karşılık **9.661 benzersiz metin** var. Yani bazı ilanlar aynı özet metnini paylaşıyor. `job_link` benzersiz olduğu için bu bir tekrar sorunu oluşturmuyor, ama metin analizi yaparsam aklımda tutmalıyım.

In [23]:
df_posting["job_link"].duplicated().sum()

np.int64(0)

In [24]:
df_posting.nunique()

job_link               12217
last_processed_time     5763
last_status                1
got_summary                1
got_ner                    1
is_being_worked            1
job_title               6484
company                 3947
job_location            2049
first_seen                 6
search_city              801
search_country             4
search_position          711
job_level                  2
job_type                   3
dtype: int64

In [25]:
df_skills.nunique()

job_link      12217
job_skills    12204
dtype: int64

In [26]:
df_summary.nunique()

job_link       12217
job_summary     9661
dtype: int64

### 2.4 Benzersiz değer sayıları
`job_postings` için `nunique()` sonuçlarından çıkardıklarım:
- `last_status`, `got_summary`, `got_ner` ve `is_being_worked` sütunlarında **yalnızca 1 benzersiz değer** var. Her satırda aynı değer olan bir sütun satırları birbirinden ayırt etmediği için analizde bilgi taşımıyor. Bu sütunlar için ne yapacağıma temizleme bölümünde karar vereceğim.
- Kategorik sütunlar küçük sayıda gruba sahip: `search_country` 4, `job_level` 2, `job_type` 3 benzersiz değer içeriyor. Bu sütunlar gruplama ve grafik için uygun.
- `first_seen` sadece 6 farklı tarih içeriyor, yani ilanlar çok kısa bir zaman aralığında toplanmış.

In [27]:
df_posting[df_posting["job_link"].isin(df_skills["job_link"])].head()

,job_link,last_processed_time,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
0,https://www.linkedin.com/jobs/view/senior-mach...,2024-01-21 08:08:48.031964+00,Finished NER,t,t,f,Senior Machine Learning Engineer,Jobs for Humanity,"New Haven, CT",2024-01-14,East Haven,United States,Agricultural-Research Engineer,Mid senior,Onsite
1,https://www.linkedin.com/jobs/view/principal-s...,2024-01-20 04:02:12.331406+00,Finished NER,t,t,f,"Principal Software Engineer, ML Accelerators",Aurora,"San Francisco, CA",2024-01-14,El Cerrito,United States,Set-Key Driver,Mid senior,Onsite
2,https://www.linkedin.com/jobs/view/senior-etl-...,2024-01-21 08:08:31.941595+00,Finished NER,t,t,f,Senior ETL Data Warehouse Specialist,Adame Services LLC,"New York, NY",2024-01-14,Middletown,United States,Technical Support Specialist,Associate,Onsite
3,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:30:55.796572+00,Finished NER,t,t,f,Senior Data Warehouse Developer / Architect,Morph Enterprise,"Harrisburg, PA",2024-01-12,Lebanon,United States,Architect,Mid senior,Onsite
4,https://www.linkedin.com/jobs/view/lead-data-e...,2024-01-21 08:08:58.312124+00,Finished NER,t,t,f,Lead Data Engineer,Dice,"Plano, TX",2024-01-14,McKinney,United States,Maintenance Data Analyst,Mid senior,Onsite

In [28]:
df_posting[df_posting["job_link"].isin(df_summary["job_link"])]

,job_link,last_processed_time,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
0,https://www.linkedin.com/jobs/view/senior-mach...,2024-01-21 08:08:48.031964+00,Finished NER,t,t,f,Senior Machine Learning Engineer,Jobs for Humanity,"New Haven, CT",2024-01-14,East Haven,United States,Agricultural-Research Engineer,Mid senior,Onsite
1,https://www.linkedin.com/jobs/view/principal-s...,2024-01-20 04:02:12.331406+00,Finished NER,t,t,f,"Principal Software Engineer, ML Accelerators",Aurora,"San Francisco, CA",2024-01-14,El Cerrito,United States,Set-Key Driver,Mid senior,Onsite
2,https://www.linkedin.com/jobs/view/senior-etl-...,2024-01-21 08:08:31.941595+00,Finished NER,t,t,f,Senior ETL Data Warehouse Specialist,Adame Services LLC,"New York, NY",2024-01-14,Middletown,United States,Technical Support Specialist,Associate,Onsite
3,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:30:55.796572+00,Finished NER,t,t,f,Senior Data Warehouse Developer / Architect,Morph Enterprise,"Harrisburg, PA",2024-01-12,Lebanon,United States,Architect,Mid senior,Onsite
4,https://www.linkedin.com/jobs/view/lead-data-e...,2024-01-21 08:08:58.312124+00,Finished NER,t,t,f,Lead Data Engineer,Dice,"Plano, TX",2024-01-14,McKinney,United States,Maintenance Data Analyst,Mid senior,Onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12212,https://uk.linkedin.com/jobs/view/data-reporti...,2024-01-21 07:11:22.099082+00,Finished NER,t,t,f,"Data Reporting Manager, FOOTBALL ASSOCIATION",Guardian Jobs,"Wembley, England, United Kingdom",2024-01-16,High Wycombe,United Kingdom,Manager Forms Analysis,Mid senior,Onsite
12213,https://www.linkedin.com/jobs/view/corporate-a...,2024-01-19 15:10:41.177008+00,Finished NER,t,t,f,Corporate AML Alert Investigation Specialist,"Glacier Bancorp, Inc.","Kalispell, MT",2024-01-14,Montana,United States,Teller,Mid senior,Onsite
12214,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:20:19.036168+00,Finished NER,t,t,f,Senior Data Scientist,Highnote,"San Francisco, CA",2024-01-16,San Rafael,United States,Mathematician,Mid senior,Onsite
12215,https://www.linkedin.com/jobs/view/senior-data...,2024-01-19 23:25:28.107523+00,Finished NER,t,t,f,Senior Data Engineer,CompSource Mutual Insurance Company,"Oklahoma City, OK",2024-01-16,Arcadia,United States,Protection Engineer,Mid senior,Onsite
12216,https://www.linkedin.com/jobs/view/medical-tec...,2024-01-19 23:26:27.593516+00,Finished NER,t,t,f,"Medical Technologist, MLS or MLT",Community Health Systems,"Mooresville, NC",2024-01-14,Salisbury,United States,Biologist,Mid senior,Onsite

## 3. Birleştirme öncesi anahtar kontrolleri
Üç tabloyu `job_link` sütunu üzerinden birleştireceğim. Yanlış bir birleştirme satırları çoğaltabilir veya kaybettirebilir. Bu yüzden önce şunları kontrol ediyorum:

1. `job_link` değerleri her tabloda **benzersiz** mi?
2. Bir tablodaki linkler diğer tablolarda **bulunuyor** mu? (iki yönde)
3. `job_link` sütunlarında **eksik değer** var mı?

In [29]:
df_skills["job_link"].isin(df_summary["job_link"]).sum()

np.int64(12217)

In [30]:
df_summary["job_link"].isin(df_skills["job_link"]).sum()

np.int64(12217)

In [31]:
df_posting["job_link"].isin(df_skills["job_link"]).sum()

np.int64(12217)

In [32]:
df_skills["job_link"].isin(df_posting["job_link"]).sum()

np.int64(12217)

In [33]:
df_posting["job_link"].isin(df_summary["job_link"]).sum()

np.int64(12217)

In [34]:
df_summary["job_link"].isin(df_posting["job_link"]).sum()

np.int64(12217)

In [35]:
df_posting["job_link"].nunique()

12217

In [36]:
df_skills["job_link"].nunique()

12217

In [37]:
df_summary["job_link"].nunique()

12217

In [38]:
df_posting["job_link"].isnull().sum()

np.int64(0)

In [39]:
df_summary["job_link"].isnull().sum()

np.int64(0)

In [40]:
df_skills["job_link"].isnull().sum()

np.int64(0)

**Kontrol sonuçları:**
- `job_link` her üç tabloda da 12.217 benzersiz değer içeriyor, yani tekrar eden anahtar yok.
- `isin()` ile her tablonun linklerini diğer iki tabloda aradım, her iki yönde de **12.217 eşleşme** çıktı. Yani linkler tamamen aynı kümeden geliyor.
- Hiçbir tabloda `job_link` eksik değil.

**Sonuç:** Üç tablo `job_link` üzerinden **birebir (one-to-one)** ilişkili. Birleştirme sırasında satır kaybı veya çoğalma beklemiyorum.

In [41]:
df_posting[df_posting["job_location"].isnull()]

,job_link,last_processed_time,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
9885,https://www.linkedin.com/jobs/view/sr-data-eng...,2024-01-20 04:25:45.213731+00,Finished NER,t,t,f,"Sr. Data Engineer, Abuse Test & Engineering",Tesla,NaN,2024-01-17,Alameda,United States,Test Engineer Mechanical Equipment,Mid senior,Onsite

Eksik `job_location` değerine sahip tek satır bir **Tesla** ilanı (`Sr. Data Engineer, Abuse Test & Engineering`). `search_city` sütunu "Alameda" gösteriyor, ancak `search_city` ilanın gerçek konumu değil, **ilanın aranırken kullanılan şehir**. İlk satırlarda da buna benzer farklar var (örneğin `job_location` "New Haven, CT" iken `search_city` "East Haven"). Bu yüzden `search_city` ile doldurmak yanlış bilgi eklemek olabilir.

**Kararım:**
 Beceri analizinde bu ilanın bilgisi kullanılmaya devam eder, konum grafiğinde dışarıda bırakılır.

## 4. Tabloların birleştirilmesi
`job_postings` ana tablom olduğu için `how="left"` ile birleştiriyorum. Böylece ana tablodaki hiçbir satır kaybolmaz. Anahtarlar tamamen eşleştiği için `inner` de aynı sonucu verirdi, ama `left` niyetimi (ana tabloyu korumak) açıkça gösteriyor.

Önce `job_skills`'i, sonra `job_summary`'yi ekliyorum.

In [42]:
sonuc = df_posting.merge(df_skills, on="job_link", how="left")

In [43]:
sonuc2=sonuc.merge(df_summary,on="job_link",how="left")

In [44]:
sonuc2.head()

,job_link,last_processed_time,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type,job_skills,job_summary
0,https://www.linkedin.com/jobs/view/senior-mach...,2024-01-21 08:08:48.031964+00,Finished NER,t,t,f,Senior Machine Learning Engineer,Jobs for Humanity,"New Haven, CT",2024-01-14,East Haven,United States,Agricultural-Research Engineer,Mid senior,Onsite,"Machine Learning, Programming, Python, Scala, ...",Company Description\nJobs for Humanity is part...
1,https://www.linkedin.com/jobs/view/principal-s...,2024-01-20 04:02:12.331406+00,Finished NER,t,t,f,"Principal Software Engineer, ML Accelerators",Aurora,"San Francisco, CA",2024-01-14,El Cerrito,United States,Set-Key Driver,Mid senior,Onsite,"C++, Python, PyTorch, TensorFlow, MXNet, CUDA,...",Who We Are\nAurora (Nasdaq: AUR) is delivering...
2,https://www.linkedin.com/jobs/view/senior-etl-...,2024-01-21 08:08:31.941595+00,Finished NER,t,t,f,Senior ETL Data Warehouse Specialist,Adame Services LLC,"New York, NY",2024-01-14,Middletown,United States,Technical Support Specialist,Associate,Onsite,"ETL, Data Integration, Data Transformation, Da...","Location: New York City, NY\nPosition Summary\..."
3,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:30:55.796572+00,Finished NER,t,t,f,Senior Data Warehouse Developer / Architect,Morph Enterprise,"Harrisburg, PA",2024-01-12,Lebanon,United States,Architect,Mid senior,Onsite,"Data Lakes, Data Bricks, Azure Data Factory Pi...",Responsibilities:\nCandidate must have signifi...
4,https://www.linkedin.com/jobs/view/lead-data-e...,2024-01-21 08:08:58.312124+00,Finished NER,t,t,f,Lead Data Engineer,Dice,"Plano, TX",2024-01-14,McKinney,United States,Maintenance Data Analyst,Mid senior,Onsite,"Java, Scala, Python, RDBMS, NoSQL, Redshift, S...",Dice is the leading career destination for tec...

In [45]:
sonuc2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12217 entries, 0 to 12216
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_link             12217 non-null  object
 1   last_processed_time  12217 non-null  object
 2   last_status          12217 non-null  object
 3   got_summary          12217 non-null  object
 4   got_ner              12217 non-null  object
 5   is_being_worked      12217 non-null  object
 6   job_title            12217 non-null  object
 7   company              12217 non-null  object
 8   job_location         12216 non-null  object
 9   first_seen           12217 non-null  object
 10  search_city          12217 non-null  object
 11  search_country       12217 non-null  object
 12  search_position      12217 non-null  object
 13  job_level            12217 non-null  object
 14  job_type             12217 non-null  object
 15  job_skills           12212 non-null  object
 16  job_summary          12217 non-null  object
dtypes: object(17)
memory usage: 1.6+ MB

In [46]:
sonuc2["job_link"].isnull().sum()

np.int64(0)

In [47]:
sonuc2.shape

(12217, 17)

In [48]:
sonuc2["job_link"].duplicated().sum()

np.int64(0)

In [49]:
df = sonuc2.copy()

**Birleştirme sonucu doğrulama:**
- Birleşik tablo **12.217 satır ve 17 sütun** (15 + `job_skills` + `job_summary`). Satır sayısı değişmedi.
- `job_link` içinde eksik ve tekrar eden değer yok.
- Eksik değerler birleştirmeden önceki hâliyle aynı: `job_location`'da 1, `job_skills`'te 5.

Artık tek bir tablom var, temizlemeye bu tablo üzerinden devam ediyorum.

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12217 entries, 0 to 12216
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_link             12217 non-null  object
 1   last_processed_time  12217 non-null  object
 2   last_status          12217 non-null  object
 3   got_summary          12217 non-null  object
 4   got_ner              12217 non-null  object
 5   is_being_worked      12217 non-null  object
 6   job_title            12217 non-null  object
 7   company              12217 non-null  object
 8   job_location         12216 non-null  object
 9   first_seen           12217 non-null  object
 10  search_city          12217 non-null  object
 11  search_country       12217 non-null  object
 12  search_position      12217 non-null  object
 13  job_level            12217 non-null  object
 14  job_type             12217 non-null  object
 15  job_skills           12212 non-null  object
 16  job_summary          12217 non-null  object
dtypes: object(17)
memory usage: 1.6+ MB

**last_processed_time sutünün tipinin düzeltilmesi**

1.Tarihe göre sıralama, gün/ay çıkarma gibi işlemleri için:

2.Önce object tipindeki sütunu `to_datetime` fonksiyonu ile datetime dönüştürdüm.


3.UTC, saat dilimi bilgisini `dt.tz_localize(None)` fonksiyonu ile kaldırdım


4.Saniyenin altını `dt.floor()` fonksiyonunu kullanarak kaldırdım


5.Sonuç olarak sütunun tipi saat dilimsiz datetime64[ns] Oldu.

In [51]:
df["last_processed_time"]=pd.to_datetime(df["last_processed_time"])

In [52]:
df["last_processed_time"].dtype

datetime64[ns, UTC]

In [53]:
df["last_processed_time"] = df["last_processed_time"].dt.tz_localize(None)

In [54]:
df["last_processed_time"]=df["last_processed_time"].dt.floor("s")

In [55]:
df["last_processed_time"].dtype

dtype('<M8[ns]')

**first_seen sutünün tipinin düzeltilmesi**

object tipindeki sütunu `to_datetime` fonksiyonu ile datetime dönüştürdüm.

In [56]:
df["first_seen"]=pd.to_datetime(df["first_seen"])

In [57]:
df["first_seen"].dtype

dtype('<M8[ns]')

## 5. Rolleri gruplamak, alan dışı rolleri temizlemek.

Amacım veri bilimi ve makine öğrenmesiyle ilgili ilanların becerilerini incelemek. `search_position` arama sırasında kullanılan terimi gösterdiği için gerçek ilan rolü olarak kullanmıyorum; sınıflandırmada `job_title` alanını ve gerektiğinde `job_skills` içeriğini dikkate alıyorum.

İlk sınıflandırma başlık anahtar sözcükleriyle yapılır. Bu otomatik etiketleme yalnızca ilk adımdır; belirsiz eşleşmeler elle kontrol edilip düzeltilir. İlanları silmek yerine `rol_grubu` etiketiyle tutuyorum; böylece kaynak kayıtlar korunur. Data center ve data entry ilanları bu analizin kapsamı dışında bırakılıp `İlgisiz` grubuna alınır.

In [58]:
baslik = df["job_title"].fillna("").astype(str).str.lower()

dislanan = baslik.str.contains(
    r"data\s?cent(?:er|re)|datacent(?:er|re)|data entry", regex=True,na=False
)

ilgili = baslik.str.contains(
    r"data|machine learning|\bml\b|\bai\b|analyst|analytics|scientist|"
    r"database|\bdba\b|\bsql\b|\betl\b|statistic|business intelligence|\bbi\b|mlops",
    regex=True,na=False
)

df["rol_grubu"] = np.select(
    [dislanan, ilgili],
    ["Dışlanan (data center/entry)", "Data & ML"],
    default="İlgisiz"
)

print(df["rol_grubu"].value_counts())

rol_grubu
Data & ML                       10414
Dışlanan (data center/entry)     1061
İlgisiz                           742
Name: count, dtype: int64

In [59]:
print(baslik[dislanan].str.contains("entry").sum(), "data entry") #baslik burada bir metin serisi. dislanan: Aynı uzunlukta bir True/False serisi.
print(baslik[dislanan].str.contains("cent").sum(), "data center")

257 data entry
804 data center

## 6. Başlıkları inceleyip doğru ayırım sağlanmış mı kontrol ediyoruz.
Başlık anahtar sözcükleri tek başına yeterli olmayabilir: örneğin “MLS” tıp laboratuvarı anlamına gelebilir, “AML” ise makine öğrenmesinden farklı bir alanı gösterebilir. Bu yüzden beceri metniyle ilgili görünen adayları kontrol ettim ve aşağıdaki satırları manuel olarak yeniden etiketledim. Bu liste, önceki incelemede verdiğim kararları kodda görünür ve tekrarlanabilir tutar

Doğru veri demek doğru analiz demektir. Bu yüzden bu adım çok önemli.

sample() fonksiyonu ile rastgele satırlar getirip titleler arasında yanlış eşleşme var mı diye kontrol ederiz varsa doğru gruba atarız.

In [60]:
df.loc[df["rol_grubu"] == "İlgisiz", "job_title"].sample(10, random_state=1)

4807                               AML/CFT Program Manager
7730                Service Supervisor - Citizen House MLK
9473     MLT - Medical Laboratory Technician - Worthing...
9114     Microbiology Lead (MT, MLT, MLS) - $5,000 - $1...
12056                 Manager, Anti-Money Laundering (AML)
5750                        Medical Technologist (MT, MLS)
7739           BSA/AML/OFAC Department Manager [Full-Time]
2970                      Medical Lab Technician (MLT) PRN
10851                         SEN Tutors Needed in Bromley
7480     Registered Nurse | Intensive Care Unit (Kamloo...
Name: job_title, dtype: object

In [61]:
df.loc[df["rol_grubu"] == "Data & ML", "job_title"].sample(10, random_state=1)

4291                     Senior Data Engineer (1021882)
9513                           Data and Funding Manager
10704                   Staff Machine Learning Engineer
4703                   Senior Machine Learning Engineer
4913     Data Domain Architect Lead, Workforce Planning
3857                             Associate Data Analyst
817                               Senior Data Scientist
4406                              Research Data Analyst
1728                   Data Governance Analyst (Hybrid)
5724                           Data Solutions Architect
Name: job_title, dtype: object

In [62]:
df.loc[11324, ["job_title","job_skills"]]

job_title       Senior MLS Engineer, Autonomous Driving Startup
job_skills    Software Development, Computer Science, Data I...
Name: 11324, dtype: object

In [63]:
#Başlıkta "engineer" geçen ve "mls" içerenleri yakala
mls_muhendis = baslik.str.contains(r"\bmls\b") & baslik.str.contains("engineer")
df.loc[mls_muhendis, ["job_title","job_skills","rol_grubu"]]

,job_title,job_skills,rol_grubu
443,"Senior MLS Engineer, Autonomous Driving Startup","Embedded Systems, FaultTolerant Distributed Ru...",İlgisiz
944,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Autonomous Driving, Arti...",İlgisiz
1025,"Senior MLS Engineer, Autonomous Driving Startup","Embedded Systems, FaultTolerant Systems, Distr...",İlgisiz
1133,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Distributed Systems, Ope...",İlgisiz
1354,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Computer Science, FaultT...",İlgisiz
1441,"Senior MLS Engineer, Autonomous Driving Startup","Faulttolerant distributed runtime systems, Dom...",İlgisiz
1863,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Embedded systems, Faultt...",İlgisiz
1969,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Distributed systems, Ope...",İlgisiz
2186,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Autonomous Driving, Mach...",İlgisiz
2740,"Senior MLS Engineer, Autonomous Driving Startup","AI, Apache Spark, Autonomous Driving, Big Data...",İlgisiz
3079,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Computer Science, System...",İlgisiz
4676,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Embedded Systems, Data a...",İlgisiz
5341,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Distributed Systems, Ope...",İlgisiz
5345,"Senior MLS Engineer, Autonomous Driving Startup","Data Science, Machine Learning, Faulttolerant ...",İlgisiz
8092,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, FaultTolerant Distribute...",İlgisiz
8100,"Senior MLS Engineer, Autonomous Driving Startup","Software Engineering, Autonomous Driving, Arti...",İlgisiz
8101,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Systems Engineering, Dis...",İlgisiz
8344,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Systems Engineering, Dis...",İlgisiz
9244,"Senior MLS Engineer, Autonomous Driving Startup","Software Engineering, Machine Learning Enginee...",İlgisiz
9329,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Embedded Systems, Distri...",İlgisiz
9378,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Systems Engineering, Dis...",İlgisiz
9526,"Senior MLS Engineer, Autonomous Driving Startup","Apache Spark, Compilers, Distributed databases...",İlgisiz
9564,"Senior MLS Engineer, Autonomous Driving Startup","Cloudbased systems, Distributed systems, Opens...",İlgisiz
9790,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Systems Engineering, Com...",İlgisiz
9982,"Senior MLS Engineer, Autonomous Driving Startup","Computer Science, Software development, Distri...",İlgisiz
10080,"Senior MLS Engineer, Autonomous Driving Startup","Software Engineering, Embedded Systems, Faultt...",İlgisiz
10110,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Autonomous Driving Syste...",İlgisiz
10154,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Embedded systems, Data a...",İlgisiz
10436,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Faulttolerant distribute...",İlgisiz
10446,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Data Platforms, CloudBas...",İlgisiz
10487,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Embedded systems, Faultt...",İlgisiz
10502,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Embedded Systems, Faultt...",İlgisiz
10543,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Distributed Systems, Dat...",İlgisiz
10626,"Senior MLS Engineer, Autonomous Driving Startup","Embedded Systems, Autonomous Vehicles, Data Ce...",İlgisiz
10631,"Senior MLS Engineer, Autonomous Driving Startup","Autonomous driving software, Artificial intell...",İlgisiz
11007,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Embedded Systems, Distri...",İlgisiz
11061,"Senior MLS Engineer, Autonomous Driving Startup","Software Development Experience, Data Platform...",İlgisiz
11168,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Distributed Systems, Dat...",İlgisiz
11324,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Computer Science, Data I...",İlgisiz
11345,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Systems engineering, Dis...",İlgisiz
11412,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Distributed systems, Ope...",İlgisiz
11504,"Senior MLS Engineer, Autonomous Driving Startup","Software development, General software enginee...",İlgisiz
11711,"Senior MLS Engineer, Autonomous Driving Startup","Embedded Systems, Autonomous Vehicles, Data Ce...",İlgisiz
11767,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, General Software Enginee...",İlgisiz
11988,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Systems Engineering, Dis...",İlgisiz

In [64]:
# Başlığında MLS geçen mühendis ilanlarını Data & ML olarak düzelt
mls_muhendis=(
    baslik.str.contains(r"\bmls\b",na=False) # na=False parametresi şunu söyler: Eğer bu satırda hiçbir şey yazmıyorsa veri boşsa/NaN ise doğrudan False kabul et ve aramaya devam et.
    & baslik.str.contains("engineer",na=False)
)

df.loc[mls_muhendis, "rol_grubu"] = "Data & ML"

df.loc[mls_muhendis, ["job_title","job_skills","rol_grubu"]]

,job_title,job_skills,rol_grubu
443,"Senior MLS Engineer, Autonomous Driving Startup","Embedded Systems, FaultTolerant Distributed Ru...",Data & ML
944,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Autonomous Driving, Arti...",Data & ML
1025,"Senior MLS Engineer, Autonomous Driving Startup","Embedded Systems, FaultTolerant Systems, Distr...",Data & ML
1133,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Distributed Systems, Ope...",Data & ML
1354,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Computer Science, FaultT...",Data & ML
1441,"Senior MLS Engineer, Autonomous Driving Startup","Faulttolerant distributed runtime systems, Dom...",Data & ML
1863,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Embedded systems, Faultt...",Data & ML
1969,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Distributed systems, Ope...",Data & ML
2186,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Autonomous Driving, Mach...",Data & ML
2740,"Senior MLS Engineer, Autonomous Driving Startup","AI, Apache Spark, Autonomous Driving, Big Data...",Data & ML
3079,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Computer Science, System...",Data & ML
4676,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Embedded Systems, Data a...",Data & ML
5341,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Distributed Systems, Ope...",Data & ML
5345,"Senior MLS Engineer, Autonomous Driving Startup","Data Science, Machine Learning, Faulttolerant ...",Data & ML
8092,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, FaultTolerant Distribute...",Data & ML
8100,"Senior MLS Engineer, Autonomous Driving Startup","Software Engineering, Autonomous Driving, Arti...",Data & ML
8101,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Systems Engineering, Dis...",Data & ML
8344,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Systems Engineering, Dis...",Data & ML
9244,"Senior MLS Engineer, Autonomous Driving Startup","Software Engineering, Machine Learning Enginee...",Data & ML
9329,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Embedded Systems, Distri...",Data & ML
9378,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Systems Engineering, Dis...",Data & ML
9526,"Senior MLS Engineer, Autonomous Driving Startup","Apache Spark, Compilers, Distributed databases...",Data & ML
9564,"Senior MLS Engineer, Autonomous Driving Startup","Cloudbased systems, Distributed systems, Opens...",Data & ML
9790,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Systems Engineering, Com...",Data & ML
9982,"Senior MLS Engineer, Autonomous Driving Startup","Computer Science, Software development, Distri...",Data & ML
10080,"Senior MLS Engineer, Autonomous Driving Startup","Software Engineering, Embedded Systems, Faultt...",Data & ML
10110,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Autonomous Driving Syste...",Data & ML
10154,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Embedded systems, Data a...",Data & ML
10436,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Faulttolerant distribute...",Data & ML
10446,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Data Platforms, CloudBas...",Data & ML
10487,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Embedded systems, Faultt...",Data & ML
10502,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Embedded Systems, Faultt...",Data & ML
10543,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Distributed Systems, Dat...",Data & ML
10626,"Senior MLS Engineer, Autonomous Driving Startup","Embedded Systems, Autonomous Vehicles, Data Ce...",Data & ML
10631,"Senior MLS Engineer, Autonomous Driving Startup","Autonomous driving software, Artificial intell...",Data & ML
11007,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Embedded Systems, Distri...",Data & ML
11061,"Senior MLS Engineer, Autonomous Driving Startup","Software Development Experience, Data Platform...",Data & ML
11168,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Distributed Systems, Dat...",Data & ML
11324,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Computer Science, Data I...",Data & ML
11345,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Systems engineering, Dis...",Data & ML
11412,"Senior MLS Engineer, Autonomous Driving Startup","Software development, Distributed systems, Ope...",Data & ML
11504,"Senior MLS Engineer, Autonomous Driving Startup","Software development, General software enginee...",Data & ML
11711,"Senior MLS Engineer, Autonomous Driving Startup","Embedded Systems, Autonomous Vehicles, Data Ce...",Data & ML
11767,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, General Software Enginee...",Data & ML
11988,"Senior MLS Engineer, Autonomous Driving Startup","Software Development, Systems Engineering, Dis...",Data & ML

İlgisiz olarak adlandırdığımız başlıkta gözümüzden kaçan var mı diye kontrol ediyoruz.
Çıktılar çok uzun olduğu için eklemedim.

In [65]:
ilgisiz_basliklar = df.loc[
    df["rol_grubu"] == "İlgisiz", ["job_title"]
].value_counts()

ilgisiz_basliklar.iloc[:40]

job_title
Registered Nurse | Intensive Care Unit (Kamloops, BC) - Potential Relocation Assistance     15
Manager, Anti-Money Laundering (AML)                                                        13
2024 MLB Gameday Compliance Monitor (Seasonal)                                              12
Medical Laboratory Technologist - MT / Medical Laboratory Technologist - MLT                11
Medical Technologist MT or MLT                                                              10
MLT                                                                                         10
Registered Nurse Intensive Care Unit (Kamloops, BC) - Potential Relocation Assistance        9
Medical Technologist MT or Medical Lab Technician MLT - Laboratory                           8
Medical Lab Technologist (MLT)                                                               8
Medical Technologist/MLS                                                                     6
Medical Technologist/ MLT - PRN                                                              6
MLT - Medical Laboratory Technologist                                                        6
MT/MLS                                                                                       6
BSA/AML Investigator I                                                                       5
Medical Technologist/MLT - Full Time                                                         5
Medical Laboratory Technologist (MLT)                                                        5
Medical Technologist/ MLT - Full Time *Sign On*                                              5
Medical Technologist/MLT - Full Time *Sign On*                                               4
Medical Technologist (MT/MLT) - Competitive Pay + Sign on bonus                              4
Medical Technologist/ MLT - Full Time Weekend Nights *Sign On*                               4
Medical Technologist (MT, MLS)                                                               4
Medical Technologist (MT/MLT) - Competitive Package                                          4
MLS Coordinator                                                                              4
Medical Laboratory Technician (MLT)                                                          4
Senior Compiler Engineer – MLIR                                                              3
Medical Technologist/MLT                                                                     3
BSA/AML Compliance Specialist I                                                              3
BSA/AML Officer                                                                              3
AML & Compliance Manager                                                                     3
RN Care Manager- MLTC (Managed Long Term Care) at Elderwood/Pediatric/PostAcute/Woodmark     3
Lab Technical Sec Lead-MT/MLS                                                                3
Consultant CAMHS Bromley Adolescent                                                          3
Medical Technologist / Medical Lab Technician (MLS, MT, MLT) - Maine Medical Center Lab      3
Medical Technologist MLT                                                                     3
Medical Technologist / Medical Lab Technician (MLS, MT, MLT) - Blood Bank                    3
Phlebotomist Part Time - PAML                                                                3
Assistant Salon Manager - Hamlin Plaza                                                       3
Part Time Phlebotomist - PAML                                                                3
Senior Risk Manager - Anti-Money Laundering (AML)                                            2
Workshop Supervisor in Cramlington, UK                                                       2
Name: count, dtype: int64

In [66]:
#ilgisiz_basliklar = df.loc[
#    df["rol_grubu"] == "İlgisiz", ["job_title", "job_skills"]
#].value_counts()

#ilgisiz_basliklar.iloc[40:80]

In [67]:
#ilgisiz_basliklar = df.loc[
#   df["rol_grubu"] == "İlgisiz", ["job_title", "job_skills"]
#].value_counts()

#ilgisiz_basliklar.iloc[80:120]

In [68]:
#ilgisiz_basliklar = df.loc[
#    df["rol_grubu"] == "İlgisiz", ["job_title", "job_skills"]
#].value_counts()

#ilgisiz_basliklar.iloc[120:160]

In [69]:
df["rol_grubu"].str.contains("İlgisiz").sum()

np.int64(697)

In [70]:
aiml_profesor = (
    baslik.str.contains("assistant professor", na=False)
    & baslik.str.contains("aiml", na=False)
)

df.loc[aiml_profesor, ["job_title", "job_skills", "rol_grubu"]]

,job_title,job_skills,rol_grubu
7902,Assistant Professor - Computer Science AIML,"Computer Science (PhD), Research, Teaching (Un...",İlgisiz

In [71]:
df.loc[aiml_profesor, "rol_grubu"] = "Data & ML"

In [72]:
print("İlgisiz ilan satırı:", (df["rol_grubu"] == "İlgisiz").sum())
print("Farklı başlık:", len(ilgisiz_basliklar))

İlgisiz ilan satırı: 696
Farklı başlık: 473

In [73]:
ilgili_beceri = (
    r"machine learning|deep learning|data science|data engineering|"
    r"data scientist|artificial intelligence|computer vision|"
    r"natural language processing|\bnlp\b|mlops|"
    r"predictive modeling|statistical modeling"
)

beceri_adayi = (
    (df["rol_grubu"] == "İlgisiz")
    & df["job_skills"].str.contains(ilgili_beceri, case=False, na=False)
)

adaylar = df.loc[beceri_adayi, ["job_title", "job_skills"]]

print("İncelenecek aday ilan:", len(adaylar))
adaylar

İncelenecek aday ilan: 15

,job_title,job_skills
382,Senior Compiler Engineer – MLIR,"PTX, GPU Computing, Deep Learning, Autonomous ..."
937,Medical Technologist: MT/MLT/MLS/CLS/Bachelor ...,"Medical Technologist (MT MLS MLT CLS), Baccala..."
2698,Medical Technologist: MT/MLT/MLS/BS in Biology...,"Microbiology, Molecular Microbiology, Laborato..."
5057,Helen Hamlyn Professor of Design,"Research, Inclusive Design, Design for Healthc..."
5220,AIML Developer,"Python, TensorFlow, PyTorch, scikitlearn, Mach..."
7936,Site Reliability Engineer - AML,"Site Reliability Engineering, Applied Machine ..."
9142,Technical Lead AIML,"Generative AI, Natural Language Processing (NL..."
9457,Site Reliability Engineer - AML,"Python, C/C++, Go, Algorithms, Data structures..."
9530,Senior Compiler Engineer – MLIR,"Systems SW Compiler Engineering, PTX (Parallel..."
9582,Summer 2024 MLIR Co-Op/ Intern,"C++, Machine Learning, Compilers, Dataflow gra..."
10075,Medical Technologist: MT/MLT/MLS/CLS/Bachelor ...,"Medical Technologist (MT), MLS, MLT, CLS, Bach..."
10326,Medical Technologist: MT/MLT/MLS/CLS/Bachelor ...,"Medical Technology, Microbiology, Biology, Che..."
10971,Research Fellow-Acute Myeloid Leukemia (AML),"Hematology, Oncology, Informatics, Single cell..."
11875,Product Manager (AIML),"Product Management, Artificial Intelligence an..."
11964,Senior Compiler Engineer – MLIR,"PTX Compiler, PTX Compiler Front End, LLVM, ML..."

In [74]:
eklenecek=[382,5220,7936,9142,9457,9530,9582,11964]
df.loc[eklenecek,"rol_grubu"] = "Data & ML"

In [75]:
df["rol_grubu"].str.contains("Dışlanan (data center/entry)",regex=False,
    na=False).sum()

np.int64(1061)

In [76]:
df["rol_grubu"].value_counts()

rol_grubu
Data & ML                       10468
Dışlanan (data center/entry)     1061
İlgisiz                           688
Name: count, dtype: int64

In [77]:
df.loc[
    df["rol_grubu"] == "Data & ML",
    ["job_title", "job_skills"]
].sample(10, random_state=21)

,job_title,job_skills
7324,Data Engineer,"Data Engineering, Data Security, Data Governan..."
5361,Data Automation Engineer,"Geospatial Services and Solutions, Automation ..."
11242,Data Privacy and Security Counsel,"Legal Counseling, Data Privacy, Data Security,..."
9823,"Senior Manager, Ontology and Data Modeling","Ontology, Data Modeling, Data Standardization,..."
7380,"Director, Ontology and Data Modeling","Ontology, Data Modeling, Machine Learning, Sem..."
4423,Senior Financial Data Analyst,"SQL, Data Models, Advanced MS Office (Excel Po..."
3312,Database Administrator,"Database Administration, Oracle Administration..."
7342,Data Annotation Supervisor,"Data Annotation, Neural Networks, Artificial I..."
4952,Lead Data Scientist,"Machine Learning (ML), Artificial Intelligence..."
5577,Clinical Data Abstractor - VQI - Part Time,"VQI Registry Abstraction, EMR, Medical Termino..."

In [78]:
eklenecek=[5155,11697,3525,11632,7004]
df.loc[eklenecek,"rol_grubu"] = "İlgisizler"

In [79]:
df.loc[[661,498,3721,4896],"rol_grubu"] = "İlgisizler"

In [80]:
df.loc[[11794, 2604],"rol_grubu"] = "İlgisizler"

In [81]:
df.loc[df["rol_grubu"] == "Dışlanan (data center/entry)",["job_title","job_skills"]].sample(10,random_state=1)

,job_title,job_skills
2656,Temporary Billing Data Entry Coordinator,Data Entry
7547,Data Centre Technician,"Data Center Maintenance, Hardware Troubleshoot..."
9000,Data Center Technician 4 w/ Lab experience,"Data Center, Lab, Server, Linux, Network, Cabl..."
9272,Data Center Operations Officer,"Driver License, Access Control, Security, Alar..."
7235,Regional Cooling Service Expert (Data Center C...,"Electrotechnical education, Mechanical educati..."
4608,Data Center Engineer - Buffalo,"Server Deployment, Storage Array Configuration..."
6266,Volunteer: Data Entry Volunteer,"Personify, Google Drive, CRM software, Data en..."
9075,Data Center Operating Engineer,"Data Center Operations, UPS, Fire/Life Safety,..."
6603,Senior Data Entry Specialist,"Data Review, Cell and Molecular Biology, cGMP,..."
1396,"Public Health Adviser Data Entry, Bureau of Sc...","Data Entry, Microsoft Office Suite (Word and E..."

In [82]:
df.loc[2194,"rol_grubu"] = "Data & ML"

In [83]:
df.loc[df["rol_grubu"] == "Dışlanan (data center/entry)",
    "rol_grubu"] = "İlgisizler"

df["rol_grubu"].value_counts()

rol_grubu
Data & ML     10458
İlgisizler     1071
İlgisiz         688
Name: count, dtype: int64

In [84]:
df.loc[df["rol_grubu"] == "İlgisizler",
    "rol_grubu"] = "İlgisiz"

df["rol_grubu"].value_counts()

rol_grubu
Data & ML    10458
İlgisiz       1759
Name: count, dtype: int64

In [85]:
df["rol_grubu"].isnull().sum()

np.int64(0)

In [86]:
df["rol_grubu"].value_counts()

rol_grubu
Data & ML    10458
İlgisiz       1759
Name: count, dtype: int64

### Bu Bölümden Çıkarım
Başlık anahtar sözcükleri ilanları ilk aşamada gruplamak için işe yarıyor; ancak tek başına yeterli değil. Örnek başlıkları ve beceri metinlerini kontrol ederek, özellikle MLS gibi farklı anlamlara gelebilen kısaltmalarda ve başlığı alanla örtüşmeyen ilanlarda etiketleri düzelttim. Beceri metninde Data/ML ile ilgili terimler bulunan bazı ilanları da yeniden inceleyip uygun gruba aldım.
Bu işlemde ilanları silmedim; rol_grubu etiketlerini düzenledim. Data center ve data entry ilanlarını analiz kapsamı dışında tutup İlgisiz grubunda birleştirdim. Son hücrelerde eksik rol etiketi olup olmadığını ve grupların son sayılarını kontrol ettim.

## 7. Beceri listesini hazırlama
`job_skills` sütunundaki virgülle ayrılmış becerileri analiz edebilmek için ayrı bir `skills_list` sütununa dönüştürüyorum. Ham beceri metni `job_skills` sütununda korunur. Listeyi oluştururken boşlukları temizliyor, küçük harfe çeviriyor ve aynı ilan içindeki tekrarları kaldırıyorum. Beceri bilgisi olmayan ilanlar boş liste ([]) alır.

In [87]:
df["job_skills"] = df["job_skills"].str.strip()

In [88]:
df["job_title"] = df["job_title"].str.strip()

In [89]:
df["job_title"] = df["job_title"].str.lower()

In [90]:
# Orijinal beceri metinlerini geri getir
df["job_skills"] = sonuc2["job_skills"]

# Virgüllere göre ayır, her becerinin başındaki/sonundaki boşlukları temizle
df["skills_list"] = df["job_skills"].apply(
    lambda x: [skill.strip() for skill in x.split(",") if skill.strip()]
    if isinstance(x, str) else []
)

In [91]:
df[["job_skills", "skills_list"]].head()
df.shape

(12217, 19)

In [92]:
df["skills_list"]

0        [Machine Learning, Programming, Python, Scala,...
1        [C++, Python, PyTorch, TensorFlow, MXNet, CUDA...
2        [ETL, Data Integration, Data Transformation, D...
3        [Data Lakes, Data Bricks, Azure Data Factory P...
4        [Java, Scala, Python, RDBMS, NoSQL, Redshift, ...
                               ...
12212    [Dashboard development, Reporting, Power BI, S...
12213    [Investigation, Antimoney laundering, Fraud, B...
12214    [Data Science, Quantitative Modeling, SQL, Dat...
12215    [Data Engineering, Data Quality, SQL, Python, ...
12216    [Medical Technology, MLS, Microbiology, Clinic...
Name: skills_list, Length: 12217, dtype: object

In [93]:
df["job_skills"].isna().sum()

np.int64(5)

In [94]:
df["skills_list"].dtype

dtype('O')

In [95]:
type(df.loc[0, "skills_list"])

list

Her ilanın beceri listesini küçük harfe çevirip boşlukları temizliyoruz, boş elemanları atar ve aynı beceri listede tekrar ediyorsa tek bırakıyoruz, sırayı bozmaz.

In [96]:
df["skills_list"] = df["skills_list"].apply(
    lambda skills: list(dict.fromkeys(
        skill.strip().lower()
        for skill in skills
        if skill.strip()
    )) if isinstance(skills, list) else []
)

### Aynı becerinin farklı yazımlarını birleştirme
İlk top-15 tablosunda `communication` ve `communication skills` ayrı satırlar olarak çıkmıştı. İkisi aynı beceri olduğu için sayılar ikiye bölünüyordu. Önce `communicat` içeren yazımlara bakıyorum, sonra birleştiriyorum. Birleştirmeyi liste içinde yaptığım için bir ilanda ikisi birden geçiyorsa o ilan tek sayılır.

In [97]:
tum_beceriler = df["skills_list"].explode().value_counts()
tum_beceriler[tum_beceriler.index.str.contains("communicat", na=False)].head(10)

skills_list
communication                   2489
communication skills            1708
written communication            401
verbal communication             303
oral communication               106
strong communication skills       69
effective communication           53
data communication                46
interpersonal communication       43
written communication skills      40
Name: count, dtype: int64

In [98]:
birlestir = {"communication skills": "communication"}

df["skills_list"] = df["skills_list"].apply(
    lambda skills: list(dict.fromkeys(birlestir.get(s, s) for s in skills))
)

In [99]:
print(df.loc[0, "skills_list"])

['machine learning', 'programming', 'python', 'scala', 'java', 'data engineering', 'distributed computing', 'statistical modeling', 'optimization', 'data pipelines', 'cloud computing', 'devops', 'software development', 'data gathering', 'data preparation', 'data visualization', 'machine learning frameworks', 'scikitlearn', 'pytorch', 'dask', 'spark', 'tensorflow', 'distributed file systems', 'multi node database paradigms', 'open source ml software', 'responsible ai', 'explainable ai']

Tekrarları temizledikten sonra her ilanda tekrar olmadığını set ile doğruladım.

In [100]:
df["skills_list"].apply(lambda skills: len(skills) == len(set(skills))).all()

np.True_

İlk soruyu yanıtlıyoruz. Her beceriyi içeren kaç farklı ilan olduğunu bulup, Data & ML ilanlarının yüzde kaçında geçtiğini hesaplıyoruz. Sonra en üstteki 15 beceriyi çubuk grafiğinde gösteriyoruz.

In [101]:
df.loc[2194, "rol_grubu"]="Data & ML"

In [102]:
# Data & ML ilanları; beceri listesi boş olanları paydadan çıkar
ilanlar = df.loc[
    (df["rol_grubu"] == "Data & ML")
    & df["skills_list"].apply(bool),
    ["job_link", "skills_list"]
].copy()

In [103]:
ilan_sayisi = ilanlar["job_link"].nunique()

In [104]:
beceri_satirlari = ilanlar.explode("skills_list")

In [105]:
beceri_sayisi = (
    beceri_satirlari.groupby("skills_list")["job_link"]
    .nunique()
    .sort_values(ascending=False)
)

In [106]:
ilk15 = pd.DataFrame({
    "ilan_sayisi": beceri_sayisi.head(15),
    "yuzde": beceri_sayisi.head(15) / ilan_sayisi * 100
})

In [107]:
ilk15

                    ilan_sayisi      yuzde
skills_list
python                     4640  44.372191
sql                        4423  42.297026
communication              3524  33.699914
data analysis              3046  29.128813
machine learning           2613  24.988046
data visualization         2182  20.866405
data engineering           1698  16.237927
aws                        1693  16.190112
data science               1655  15.826719
tableau                    1574  15.052118
data modeling              1486  14.210577
r                          1444  13.808932
java                       1411  13.493354
project management         1407  13.455102
data management            1374  13.139524

## 8 İlk 15 beceri tablosunu yorumlama
Bu tablo, Data & ML ilanlarında en sık görülen 15 beceriyi listeler. ilan_sayisi, becerinin geçtiği farklı ilanların sayısıdır; yuzde ise bu sayının beceri listesi dolu Data & ML ilanlarının toplamına oranıdır. Örneğin yüzde 44, beceri listesi dolu ilanların yaklaşık yüzde 44’ünde o becerinin bulunduğu anlamına gelir.
Tablodaki sıralama en çok ilanda geçen beceriden başlar.

In [108]:
import matplotlib.pyplot as plt
import plotly.express as px

## 9. İlk 15 beceriyi etkileşimli grafikte gösterme
Yatay çubuk grafik becerileri ilan yüzdesine göre karşılaştırır. Çubuk uzadıkça beceri daha fazla Data & ML ilanında istenmiştir. Bir çubuğun üzerine geldiğinde becerinin geçtiği ilan sayısını ve yüzdesini görebilirsin.

In [109]:
import plotly.express as px
from IPython.display import HTML, display

grafik_df = ilk15.sort_values("yuzde").reset_index()

fig = px.bar(
    grafik_df,
    x="yuzde",
    y="skills_list",
    orientation="h",
    hover_data={
        "ilan_sayisi": True,
        "yuzde": ":.1f"
    },
    labels={
        "skills_list": "Beceri",
        "yuzde": "İlan yüzdesi",
        "ilan_sayisi": "İlan sayısı"
    },
    title="Data & ML İlanlarında En Sık İstenen 15 Beceri"
)

fig.update_layout(
    xaxis_title="İlanların yüzde kaçı?",
    yaxis_title="",
    yaxis={"categoryorder": "total ascending"}
)
fig.show()

## Kontrol: Aynı ilan birden fazla satırda olabilir mi?
Özet metinlerinin 9.661'i benzersizdi (12.217 satıra karşılık). Bazı ilanlar farklı şehir aramalarında tekrar çıkmış olabilir. Bu yüzden aynı başlık, şirket ve beceri metnine sahip satırları tek sayıp top-15 yüzdelerini karşılaştırıyorum. Sıralama değişmiyorsa sonuç tekrarlı ilanlardan etkilenmiyor demektir.

In [110]:
tekil = df.drop_duplicates(subset=["job_title", "company", "job_skills"])
print("Tüm satırlar:", len(df), "| Tekilleştirilmiş:", len(tekil))

def yuzde_serisi(veri):
    ilan = veri.loc[
        (veri["rol_grubu"] == "Data & ML") & veri["skills_list"].apply(bool),
        ["job_link", "skills_list"]
    ]
    toplam = ilan["job_link"].nunique()
    sayi = (
        ilan.explode("skills_list")
        .groupby("skills_list")["job_link"].nunique()
        .sort_values(ascending=False)
    )
    return sayi / toplam * 100

tum_yuzde = yuzde_serisi(df)
tekil_yuzde = yuzde_serisi(tekil)

karsilastirma = pd.DataFrame({
    "tum_ilanlar_yuzde": tum_yuzde,
    "tekil_ilanlar_yuzde": tekil_yuzde
}).loc[tum_yuzde.head(15).index].round(1)

karsilastirma

Tüm satırlar: 12217 | Tekilleştirilmiş: 12213

                    tum_ilanlar_yuzde  tekil_ilanlar_yuzde
skills_list
python                           44.4                 44.4
sql                              42.3                 42.3
communication                    33.7                 33.7
data analysis                    29.1                 29.1
machine learning                 25.0                 25.0
data visualization               20.9                 20.8
data engineering                 16.2                 16.2
aws                              16.2                 16.2
data science                     15.8                 15.8
tableau                          15.1                 15.0
data modeling                    14.2                 14.2
r                                13.8                 13.8
java                             13.5                 13.5
project management               13.5                 13.5
data management                  13.1                 13.1

## 10 Grafiğin yorumu

Grafikte Python (%44,4) ve SQL (%42,3) açık ara en sık görülen becerilerdir; beceri listesi dolu Data & ML ilanlarının yaklaşık her 10 tanesinden 4'ünde bu beceriler yer alır. Üçüncü sırada iletişim (%33,7) gelir. communication ve communication skills yazımları birleştirildiğinde bu sıraya çıkıyor ve ilk üçteki tek teknik olmayan beceri. Ardından veri analizi (%29,1), makine öğrenmesi (%25,0) ve veri görselleştirme (%20,9) gelir. İlk 15'te AWS, Tableau, R ve Java gibi araç ve dillerin de bulunması, teknik beklentilerin tek bir beceriyle sınırlı olmadığını gösteriyor. Her ilanda birden fazla beceri bulunabildiği için yüzdelerin toplamının 100 olması beklenmez.